modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="workshopsofdoom_datagen" #mandatory
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Workshops of Doom Datagen" #mandatory
# A text field displayed in the mod UI
authors="Commoble"
# The description text for the mod (multi line!) (#mandatory)
description='''
Data Generation is handled separately from the main mod and not packaged into the production jar
'''
